### PR TITLE
Task Send & Receive Long Polling

### PR DESCRIPTION
**Pull request by cameron-dunn-sublime**
We observe the 250ms floor latency, and according to scan times in the Strelka response it looks like it's common for this to be mostly wait time.

Also respect context cancellation in loop to ensure the loop doesn't continue.

**Describe the change**
Originally implemented in https://github.com/sublime-security/strelka/pull/23 and https://github.com/sublime-security/strelka/pull/24. The underlying code has changed with the tasks popping moved to a different file, and it looks like support for a new task structure has been added. This shouldn't affect the behavior or intention of this change though.

By using long polling to pull tasks/get results we can improve Strelka's response time, especially for files which Strelka processes extremely quickly.

**Describe testing procedures**
To test I prepared an extremely simple/small text file, and ran Strelka with the "gatekeeper" component off.

I tested each combination of blocking calls on/off for frontend and backend (each a handful of repeated calls), and recorded the E2E result time.
1. FE Blocking disabled, BE Blocking disabled: 260 - 510 ms
2. FE Blocking enabled, BE Blocking disabled: 80 - 300 ms
3. FE Blocking disabled, BE Blocking enabled: 255 - 265 ms
4. FE Blocking enabled, BE Blocking enabled: 10 - 40 ms

This pretty much matches what I would expect. With polling/blocking calls disabled on both ends a floor of 250ms is likely and a worst case is that both polls are out of sync which results in a 500 ms delay. With blocking calls enabled on either side you tend to see the result of the 250ms polling, but the worst case scenario is removed. And with both sides using blocking calls, the response time is much faster and doesn't approach 250ms.

For all of this testing I used a `5s` blocking time. This value is pretty arbitrary and won't affect the timing much because when it's exceeded we'll fast loop back to the same call. Some small notes on this:
* In the backend `continue`ing in the loop causes `time_to_live` to be checked. This means that on an idle worker, the `time_to_live` exit time could be exceeded by `blocking_pop_time_sec`. This could be prevented by using a timeout value of `min(blocking_pop_time_sec, work_expire - time.time())`, but with any moderate values this shouldn't have any real impact.
   * I'm assuming that exceeding `time_to_live` by a few seconds is low to no impact, but if not I can address this. Otherwise I don't think it's worth the even slight complexity. 
* In the frontend the `BLPop` call will `err` if the context expires while it's blocked. This is great and ensures we won't exceed the deadline while waiting for results due to the blocking calls.

**Sample output**
If this change modifies Strelka's output, then please include a sample of the output here.

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of and tested my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by ryanohoro** [comment]
There's concern from one of our engineers that long polling may cause issues with load-balanced Redis instances (e.g. Envoy). Is there a rationale for hardcoding both the long-polling approach, and the 5 second timeout duration?

**Comment by cameron-dunn-sublime** [comment]
Hey @ryanohoro, both using long polling and the timeout could definitely be made configurable.

I just did some really quick googling and found this: https://github.com/envoyproxy/envoy/issues/21783. It confirms that the commands are unsupported when using Envoy -- excellent call.

I can work on making everything configurable, defaulting to not using blocking calls to ensure backwards compatibility.

**Comment by cameron-dunn-sublime** [comment]
@ryanohoro one follow up.

I started making the changes and realized I'd need to modify the `structs` package/file. I've previously noticed because each subdirectory of `src/go/cmd` has a `go.mod` file, it's actually depending on the GitHub repo/published artifacts for the contents of `pkg`. Basically changes I make locally to `pkg/structs/structs.go` aren't  visible to `cmd/strelka-frontend`. This differs quite a bit from other Go repos I've worked with, and I haven't figured out an effective workflow. In [our fork](https://github.com/sublime-security/strelka) we have a `go.mod` file at the base of the repo which lets you depend on any local files.

Could you share anything about how you would make this type of change? Maybe I have a local Go setup issue... I've looked around and played with using `replace` in the `go.mod` file, but run into issues because `pkg` isn't in a go module.

**Comment by ryanohoro** [comment]
With regards to updating the Go code, I had run into the same problem and don't have an elegant solution. We're currently restructuring the project to separate the Go components to help reduce the friction with this.

**Comment by phutelmyer** [comment]
@cameron-dunn-sublime I'd be interested to see what you come up with for that. Definitely trying to figure out how to refactor that section of the code base.

**Comment by cameron-dunn-sublime** [comment]
@ryanohoro I've made the usage of blocking calls configurable (default off) and expanded the docs. Thanks again for catching the incompatibility with Envoy!

**Comment by ryanohoro** [comment]
Thanks so much for your contribution @cameron-dunn-sublime. I'll likely end up looking more deeply into the compatibility of long-polling for Redis behind Envoy.

**Comment by cameron-dunn-sublime** [comment]
Hey @ryanohoro, let me know if there's anything I can do. I found this: https://github.com/envoyproxy/envoy/issues/21783 which confirms the incompatibility and https://github.com/envoyproxy/envoy/pull/21843 which seems to suggest adding support won't be trivial.

Since this is configurable and defaults to not using blocking calls, there shouldn't be an issue with Envoy compatibility though.

**Comment by cameron-dunn-sublime** [comment]
@phutelmyer would you mind taking another look at this?

**Comment by phutelmyer** [comment]
@cameron-dunn-sublime Yup yup, I'll be merging this in later today after I perform some local tests.

**Pull request merged**
