### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MDixey17**
CONTRIBUTORS:
Alexis MG
Ioana Munteanu
Eileen Campbell
Maryan Said
Matthew Dixey

**Describe the change**
Include a summary of the change (with required dependencies), any issues it fixes, and relevant motivation and context.

As a capstone project for the University of Minnesota, we added 3 algorithms to Strelka: Beyond End-of-file, Least Significant Bit, and Noise Floor. There was one additional dependency of OpenCV2. A version of OpenCV was already included, but was not the correct version for our implementation.

**Describe testing procedures**
Describe the tests that you ran to verify your changes (including test configurations) and instructions so we can reproduce the tests. To assist in testing, the project maintainers may ask for file samples.

We created several images that were designed to cause the tests to flag the image in the resulting strelka.log file. These were tested repeatedly to ensure Strelka doesn't crash and produces the correct output.

**Sample output**
If this change modifies Strelka's output, then please include a sample of the output here.

**Checklist**
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of and tested my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

### CODE REVIEW

**Comment by tuduongquyet** [comment]
I suppose you are working on Windows? You may need to convert source code to LF line ending first.

**Comment by phutelmyer** [comment]
@MDixey17 - Thank you for your work on this! It looks great. I have two questions:

1. Do you have any test samples you could share to test these scanners out?
2. As @tuduongquyet noted, it looks like you may have made changes that modify how line endings are formatting. Do you mind modifying the files in this PR to accommodate? I can assist if you'd like.

Thanks again!

**Comment by tuduongquyet** [comment]
@phutelmyer yes, since I don't have permission as a maintainer of this project, so I couldn't overwrite @MDixey17's commit. I created a branch with overwritten commit at https://github.com/tuduongquyet/strelka/commit/6278d09f4cc057f439353dc11051e7292663bdae
You need to create new PR from this branch or force commit to @MDixey17 's branch.

**Comment by phutelmyer** [comment]
Thank you very much @tuduongquyet, I appreciate the effort.

@MDixey17, can you please modify your request to align with @tuduongquyet's proposed changes?
Otherwise, I can make the modification and perform testing when I find the time to do so.

**Comment by phutelmyer** [comment]
PR created based on @tuduongquyet's effort: https://github.com/target/strelka/pull/206

**Comment by phutelmyer** [comment]
Merged via https://github.com/target/strelka/pull/207

**Pull request closed without merging**
