### PR TITLE
Bump dependencies and ubuntu version

### PR DESCRIPTION
**Pull request by rhaist**
**Describe the change**

Bump dependencies to latest bug-fix version.
Bump the ubuntu base container to the new 20.04 LTS release.

**Describe testing procedures**

1. build containers
2. submit test file for every parser/plugin

### CODE REVIEW

**Comment by phutelmyer** [comment]
After building and scanning with several test filetypes, I am receiving the following error:

Scanner Issue: `scan_elf`

```
backend_1      | 2020-05-14 13:06:15 - [ERROR] root [strelka.scan_wrapper]: ScanElf: exception while scanning uid 3e925de2-a4a6-4cee-96d0-011df633f1b2 (see traceback below)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.8/dist-packages/strelka-0.0.0-py3.8.egg/strelka/strelka.py", line 148, in scan_wrapper
backend_1      |     self.scan(data, file, options, expire_at)
backend_1      |   File "/usr/local/lib/python3.8/dist-packages/strelka-0.0.0-py3.8.egg/strelka/scanners/scan_elf.py", line 9, in scan
backend_1      |     elf = ELF.parse(raw=data)
backend_1      | TypeError: parse(): incompatible function arguments. The following argument types are supported:
backend_1      |     1. (filename: str, dynsym_count_method: lief.ELF.DYNSYM_COUNT_METHODS = DYNSYM_COUNT_METHODS.AUTO) -> LIEF::ELF::Binary
backend_1      |     2. (raw: List[int], name: str = '', dynsym_count_method: lief.ELF.DYNSYM_COUNT_METHODS = DYNSYM_COUNT_METHODS.AUTO) -> LIEF::ELF::Binary
backend_1      |     3. (io: object, name: str = '') -> LIEF::ELF::Binary
backend_1      | 
backend_1      | Invoked with: kwargs: raw=b'\x7fELF\x02\<BYTES_OMITTED>
```

This error is not present on the current master build.

**Comment by rhaist** [comment]
LIEF seems to have changed the interface here. I'll check that and provide a fix.

**Comment by rhaist** [comment]
@phutelmyer Could you test again with the latest changes. I think I found the problem. The data has been passed using the `raw` parameter of LIEF. But this seems to have changed to `io` in some of the latest releases.

**Comment by phutelmyer** [comment]
Thanks for the update @rhaist! Seems like Strelka compiles fine but I ran into some error outputs with ScanElf on a few sample files. While the file processed, ScanElf threw an `uncaught_exception` flag for all files and flooded the console with bytecode (see below).

```
backend_1      | TypeError: b'\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x15\x00\x01\x00\x00\x00\xe0D\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00\xa8#\x03\x00\x00\x00\x00\x00\x02\x00\x00\x00@\x008\x00\x07\x00@\x00\x1b\x00\x1a\x00\x01\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc8k\x02\x00\x00\x00\x00\x00\xc8k\....
```

Have you been able to scan elf files successfully?

**Comment by phutelmyer** [comment]
This is unfortunately out of sync with a few files (that have been updated as part of other efforts). I appreciate the time you put into this @rhaist and if you would like to create a PR with additional versioning updates I can work with you (quicker this time) to get that implemented.

**Comment by tuduongquyet** [comment]
I'm having the same issue when executing `strelka-oneshot` on Ubuntu 20.04
``
{
  "file": {
    "depth": 0,
    "flavors": {
      "mime": [
        "application/x-executable"
      ],
      "yara": [
        "elf_file"
      ]
    },
    "scanners": [
      "ScanElf",
      "ScanEntropy",
      "ScanFooter",
      "ScanHash",
      "ScanHeader",
      "ScanYara"
    ],
    "size": 13062001,
    "tree": {
      "node": "6d9e5256-d7d3-488f-85dd-5e93b1b1fe17",
      "root": "6d9e5256-d7d3-488f-85dd-5e93b1b1fe17"
    }
  },
  "request": {
    "attributes": {
      "filename": "strelka-fileshot"
    },
    "client": "go-oneshot",
    "id": "6d9e5256-d7d3-488f-85dd-5e93b1b1fe17",
    "source": "ubuntu",
    "time": 1650963206
  },
  "scan": {
    "elf": {
      "elapsed": 0.565622,
      "flags": [
        "uncaught_exception"
      ]
    },
    "entropy": {
      "elapsed": 0.029382,
      "entropy": 6.687048940519167
    },
    "footer": {
      "elapsed": 5.4e-05,
      "footer": "me.buildVersion.str\u0000type.*\u0000runtime.textsectionmap\u0000"
    },
    "hash": {
      "elapsed": 0.188663,
      "md5": "5a710034194e1a557cac243c3dc767bc",
      "sha1": "3ebe1ba939cc985960d2810ae4156b98dcd27787",
      "sha256": "a2f91fb1e230255ffaff73028346457b916fef917648a8ec85531da69331948b",
      "ssdeep": "196608:26z7+yKMNr9Ivz1w1pVLxI+AHt+E+4e30hP:vlKuCpwvI+Aa4e30hP"
    },
    "header": {
      "elapsed": 7.7e-05,
      "header": "\u007fELF\u0002\u0001\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002\u0000>\u0000\u0001\u0000\u0000\u0000�cF\u0000\u0000\u0000\u0000\u0000@\u0000\u0000\u0000\u0000\u0000\u0000\u0000�\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
    },
    "yara": {
      "elapsed": 0.036594,
      "matches": [
        "test"
      ]
    }
  }
}
``

**Pull request closed without merging**
